/*****
 * selenium.js using web driver code, Selenium, to navigate to Aggie Access and log into with credentials that users
 * logged in on the Lily's login page.
 *****/
// Generated by Selenium IDE
//import {Builder, By, Key, until} from "selenium-webdriver";

const { Builder, By, Key, until } = require('selenium-webdriver');

const assert = require('assert');
// TODO: Enter banner id
go("","");

async function go(banner, pin) {

         let transcript = null;
        try {

            let driver = await
            new Builder().forBrowser('chrome').setChromeOptions("--headless").build();

            // Test name: tkl
            // Step # | name | target | value
            // 1 | open | /pls/NCATPROD/twbkwbis.P_WWWLogin |

            await driver.get("https://ssbprod-ncat.uncecs.edu/pls/NCATPROD/twbkwbis.P_WWWLogin");

            // 3 | type | id=UserID |

            await driver.findElement(By.id("UserID")).sendKeys(banner);
            // 4 | type | id=PIN |

            await driver.findElement(By.id("PIN")).sendKeys(pin);
            // 5 | click | css=p > input:nth-child(1) |

            await driver.findElement(By.xpath("/html/body/div[3]/form/p/input[1]")).click();
            // 7 | click | submit |

            await driver.findElement(By.xpath("//a[@href='/pls/NCATPROD/twbkwbis.P_GenMenu?name=bmenu.P_StuMainMnu']")).click();
            // 8 | click | Student Records |

            await driver.findElement(By.xpath("//a[@href='/pls/NCATPROD/twbkwbis.P_GenMenu?name=bmenu.P_AdminMnu']")).click();
            // 9 | click | Academic Transcript |

            await driver.findElement(By.xpath("//a[@href='/pls/NCATPROD/bwskotrn.P_ViewTermTran']")).click();
            // 10 | click | css=form:nth-child(2) > input |

            await driver.findElement(By.xpath("//div[3]/form/input")).click();

            transcript = await
            driver.findElement(By.xpath("/html/body/div[3]/table[1]")).getText();

            // 11 | close |  |
            console.log(transcript);
            await driver.close();
            return transcript;
        } catch (e) {
            console.log(e);
            return transcript;
        }
    }

